galaxy_info:
  author: Steffen Luetzenkirchen
  description: configures tight garbage collection for ocp4
  company: Red Hat

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: OpenShift
      versions:
        - all
  galaxy_tags:
    []

dependencies:
  []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
