---
- name: Installing KVM Packages
  yum:
    name:
      - "@virtualization-hypervisor"
      - "@virtualization-client"
      - "@virtualization-platform"
      - "@virtualization-tools"
      # ansible virt need lxml
      - python-lxml
      # ansible route53 need  python-boto
      - python-boto
      # ansible k8s need python2-openshift
      - python2-openshift
      # ansible sefcontext need policycoreutils-python
      - policycoreutils-python
    state: present

# # Update qemu to +2.4 because option fw_cfg added in 2.4 
# #  "qemu-kvm: -fw_cfg: invalid option"
# #  https://github.com/qemu/qemu/commit/81b2b81062612e
# - name: Add repos centos-release-openstack-stein
#   yum:
#     name: centos-release-openstack-stein
#     state: present

# - name: Disable all openstack repos except centos-qemu-ev
#   command: "yum-config-manager -q --disable centos-ceph-nautilus centos-nfs-ganesha28 centos-openstack-stein"

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Allow NFS traffic from VM's to Host
  firewalld:
    zone: internal
    state: enabled
    permanent: yes
    service: "{{ item }}"
  with_items:
    - nfs
    - mountd
    - rpc-bind
  notify: 'reload firewalld'

- name: Allow OpenShift traffic from VM's to Host
  firewalld:
    zone: internal
    state: enabled
    permanent: yes
    port: "{{ item }}"
  with_items:
    - 80/tcp
    - 443/tcp
    - 6443/tcp
    - 22623/tcp
  notify: 'reload firewalld'

- name: Allow OpenShift traffic from public to Host
  firewalld:
    zone: public
    state: enabled
    permanent: yes
    port: "{{ item }}"
  with_items:
    - 80/tcp
    - 443/tcp
    - 6443/tcp
  notify: 'reload firewalld'

- name: firewalld reload
  command: firewall-cmd --reload

# semanage fcontext -a -t virt_content_t "/var/lib/libvirt/images/.*\.ign"
- name: Setup fcontext for ign files
  sefcontext:
    target: '/var/lib/libvirt/images/.*\.ign'
    setype: virt_content_t
    state: present