---
hetzner_webservice_username:    # see Hetzner Robot -> Settings -> Webservice
hetzner_webservice_password:
hetzner_hostname:               # needed for Hetzner server computer name
hetzner_ip:                     # needed for Hetzner Web UI and Ansible
hetzner_autosetup_file: templates/autosetup
hetzner_disk1: sda
hetzner_disk2: sdb
hetzner_raid_level: 0
hetzner_vg_name: vg0
hetzner_image: "/root/.oldroot/nfs/install/../images/CentOS-90-stream-amd64-base.tar.gz"
hetzner_image_ignore_errors: false
hetzner_size_of_libvirt_images: all

robot_base: https://robot-ws.your-server.de/
needs_reprovision: false
already_in_rescue: false
