---
# If you like to play: ./ansible/destroy.yml --skip-tags public_dns,letsencrypt

- hosts: host
  gather_facts: true
  vars_files:
    - ../cluster.yml
  tasks:
    - name: Destroy cluster
      import_role:
        name: openshift-4-cluster
        tasks_from: destroy.yml
