---

- name: Test
  hosts: host
  connection: local
  # gather_facts: no
  vars_files:
    - ../cluster.yml
  vars:
    # post_install_add_ons:
    #   nvidia-gpu: "post-install.yaml"
  tasks:
    - import_role:
        name: openshift-4-cluster
        tasks_from: "post-install-add-ons.yml"
      when: add_ons_enabled
      tags: add-ons
