---
- name: Ensure installion directory
  file:
    path: "{{ ign_openshift_install_dir }}"
    state: directory

- name: Create install config
  template:
    src: install-config.yaml.j2
    dest: "{{ ign_openshift_install_dir }}/install-config.yaml"

- name: Save install-config from deletion
  copy:
    dest: "{{ ign_openshift_install_dir }}/install-config.yaml.original"
    src: "{{ ign_openshift_install_dir }}/install-config.yaml"

- name: Create manifest files
  command: "openshift-install --dir={{ ign_openshift_install_dir }} create manifests"
#  args:
#    creates: "{{ ign_openshift_install_dir }}/manifests/"

- name: Handle SSL certificates
  import_tasks: ssl-certificates.yml

- name: Create ignition files
  command: "openshift-install --dir={{ ign_openshift_install_dir }} create ignition-configs"
#  args:
#    creates: "{{ ign_openshift_install_dir }}/bootstrap.ign"

- name: Copy bootstrap inginition to www
  copy:
    dest: "{{ ign_http_root }}/bootstrap.ign"
    src: "{{ ign_openshift_install_dir }}/bootstrap.ign"

- name: Ensure Terraform workdir
  file:
    path: "{{ ign_terraform_workdir }}"
    state: directory
    mode: '0755'

- name: Create small ign for bootstrap
  local_action:
    module: template
    src: bootstrap-append.ign.j2
    dest: "{{ ign_terraform_workdir }}/bootstrap-append.ign"

- name: Create .kube
  file:
    path: ~/.kube
    state: directory
- name: copy the kubeconfig into .kube
  copy:
    src: "{{ ign_openshift_install_dir }}/auth/kubeconfig"
    dest: ~/.kube/config
- name: Check for the oc binary
  shell: command -v oc
  register: oc
  ignore_errors: true
- name: debug
  debug:
     msg: "{% if oc.failed == false %} Excellent! The oc binary is installed at {{ oc.stdout }}!{% else %} No oc binary found, consider installing it locally or adding it to your path!{% endif %}"
